name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Choose deploy hook
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
          elif [ "${GITHUB_REF##*/}" = "dev" ]; then
            curl -X POST "${{ secrets.VERCEL_DEV_DEPLOY_HOOK_URL }}"
          else
            echo "No deploy hook for branch ${GITHUB_REF##*/}"
          fi
