name: Frontend CI

on:
  push:
    branches: [main, dev, chore/cypress-test]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Lint, Test, and Cypress

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # Install backend and frontend dependencies
      - name: Install Backend
        run: npm ci
        working-directory: ./backend

      - name: Install Frontend
        run: npm ci
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

      - name: Start Backend
        run: npm start & npx wait-on http://localhost:8080
        working-directory: ./backend
        env:
          PORT: 8080
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Start Frontend in Background
        run: |
          npm start &
          npx wait-on http://localhost:3000
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_LOCAL_API: http://localhost:8080
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run Cypress Tests
        run: npx cypress run --browser chrome
        working-directory: ./frontend
        env:
          CYPRESS_baseUrl: http://localhost:3000
