name: Frontend CI

on:
  push:
    branches: [main, dev, chore/cypress-test]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Lint, Test, and Cypress

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # Install all dependencies
      - name: Install Backend
        run: npm ci
        working-directory: ./backend

      - name: Install Frontend
        run: npm ci
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend

      - name: Run Unit Tests
        run: npm test
        working-directory: ./frontend

      # Run Cypress with both servers
      - name: Run Cypress E2E
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          build: npm run build
          start: |
            npm --prefix ../backend start &
            npm start
          wait-on: |
            http://localhost:8080,http://localhost:3000
          wait-on-timeout: 120
        env: # environment variables for Cypress
          NEXT_PUBLIC_API_URL: "http://localhost:8080"
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
